version: '3.8'

services:
  # exporess web server
  web_honeypot:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "80:3000" # Maps localhost:80 to container:3000
    volumes:
      - ./logs/web:/usr/src/app/logs
    restart: always

  # python SSH honeypot
  ssh_honeypot:
    build:
      context: .
      dockerfile: docker/ssh/Dockerfile
    ports:
      - "22:2222" # Access via ssh admin@localhost -p 22
    volumes:
      # connects the local 'logs/ssh' folder to the container's 'log_files' folder
      - ./logs/ssh:/app/log_files
    restart: always